const fs = require('fs');

let content = fs.readFileSync('src/data.ts', 'utf8');

// 1. Add Tanzanian names to SURNAME_MAP
const tzSurnames = `  "Tanzania": ["Mushi", "Shirima", "Massawe", "Swai", "Kapinga", "Mrope", "Kileo", "Kimaro", "Lema", "Mbowe", "Makamba", "Mwinyi", "Kikwete", "Magufuli", "Suluhu", "Majaliwa", "Mwalimu", "Nyerere", "Kariuki", "Kibao", "Masanja", "Komba", "Mwandosya", "Mwakyembe", "Mdee", "Bulaya", "Mrema", "Mnyika", "Zitto", "Kabwe", "Mabula", "Ndumbaro", "Mchengerwa", "Gwajima", "Mpango", "Mwigulu", "Nchemba", "Makonda", "Chalamila", "Mtaturu", "Mhagama", "Kairuki", "Ummy", "Mwalimu", "Ndalichako", "Masele", "Nyalandu", "Membe", "Mwandosya", "Pinda", "Sumaye", "Salim", "Kigwangalla", "Nape", "Nnauye", "Makamamba", "Makani", "Slaa", "Mtei", "Mbowe", "Mbatia", "Mkosamali", "Chegeni", "Mgeja", "Ngeleja", "Chenge", "Rostam", "Dewji", "Bakhresa", "Meng", "Manji", "Karamagi", "Yona", "Mramba", "Meghji", "Kimei", "Msuya", "Malecela", "Warioba", "Salim", "Kambona", "Kawawa", "Karume", "Jumbe", "Mwinyi", "Mkapa"],`;

content = content.replace(/const SURNAME_MAP: Record<string, string\[\]> = \{/, `const SURNAME_MAP: Record<string, string[]> = {\n${tzSurnames}`);

// 2. Expand RAW_FIRST_NAMES_DB with 150+ Tanzanian names (male and female)
const tzNames = `  { first: "Juma", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Dar es Salaam" },
  { first: "Asha", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Zanzibar" },
  { first: "Baraka", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mwanza" },
  { first: "Neema", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Arusha" },
  { first: "John", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Dodoma" },
  { first: "Mary", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mbeya" },
  { first: "Daudi", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Tanga" },
  { first: "Zuhura", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Morogoro" },
  { first: "Emmanuel", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kigoma" },
  { first: "Grace", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Tabora" },
  { first: "Kelvin", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Iringa" },
  { first: "Rehema", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Shinyanga" },
  { first: "Jackson", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mtwara" },
  { first: "Fatuma", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Lindi" },
  { first: "Peter", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Songea" },
  { first: "Salome", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Sumbawanga" },
  { first: "Joseph", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Musoma" },
  { first: "Mariam", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Bukoba" },
  { first: "Michael", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Singida" },
  { first: "Amina", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kibaha" },
  { first: "David", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Babati" },
  { first: "Zainab", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Njombe" },
  { first: "Frank", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Bariadi" },
  { first: "Halima", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Geita" },
  { first: "Charles", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mpanda" },
  { first: "Hawa", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Vwawa" },
  { first: "Richard", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mafia" },
  { first: "Pili", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Pemba" },
  { first: "Simon", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Bagamoyo" },
  { first: "Mwanaidi", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kilwa" },
  { first: "Thomas", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Korogwe" },
  { first: "Mwajuma", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Lushoto" },
  { first: "James", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mombo" },
  { first: "Rukia", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Same" },
  { first: "William", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mwanga" },
  { first: "Salma", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Moshi" },
  { first: "Elias", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Rombo" },
  { first: "Tatu", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Hai" },
  { first: "Paulo", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Boma Ng'ombe" },
  { first: "Hadija", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Karatu" },
  { first: "Steven", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Monduli" },
  { first: "Ziada", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mererani" },
  { first: "George", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Tarime" },
  { first: "Husna", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Serengeti" },
  { first: "Julius", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Bunda" },
  { first: "Khadija", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Ukerewe" },
  { first: "Martin", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Magu" },
  { first: "Saida", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Misungwi" },
  { first: "Shabani", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kwimba" },
  { first: "Mwanahamis", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Sengerema" },
  { first: "Hamisi", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Geita" },
  { first: "Faiza", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Chato" },
  { first: "Saidi", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Biharamulo" },
  { first: "Pendo", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Ngara" },
  { first: "Yusuph", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Karagwe" },
  { first: "Upendo", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kyerwa" },
  { first: "Omary", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Muleba" },
  { first: "Tumaini", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Missenyi" },
  { first: "Abdallah", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kakonko" },
  { first: "Furaha", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kibondo" },
  { first: "Kassimu", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kasulu" },
  { first: "Zawadi", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Uvinza" },
  { first: "Hassan", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Buhigwe" },
  { first: "Bahati", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kaliua" },
  { first: "Ibrahim", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Urambo" },
  { first: "Farida", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Sikonge" },
  { first: "Mussa", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Uyui" },
  { first: "Mwajibu", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Igunga" },
  { first: "Salum", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Nzega" },
  { first: "Tabu", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kahama" },
  { first: "Ally", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kishapu" },
  { first: "Mwanajuma", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Msalala" },
  { first: "Rashid", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Ushetu" },
  { first: "Beti", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Meatu" },
  { first: "Ismail", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Itilima" },
  { first: "Tausi", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Busega" },
  { first: "Ramadhan", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Maswa" },
  { first: "Vumilia", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mbulu" },
  { first: "Idd", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Hanang" },
  { first: "Subira", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kiteto" },
  { first: "Jafari", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Simanjiro" },
  { first: "Shida", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mkalama" },
  { first: "Idrisa", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Iramba" },
  { first: "Mwamini", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Ikungi" },
  { first: "Rajabu", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Manyoni" },
  { first: "Sikudhani", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Itigi" },
  { first: "Athumani", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Bahi" },
  { first: "Wema", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Chamwino" },
  { first: "Bakari", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kongwa" },
  { first: "Zuwena", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mpwapwa" },
  { first: "Shaban", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kondoa" },
  { first: "Arafa", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Chemba" },
  { first: "Kassim", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kilindi" },
  { first: "Nuru", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Handeni" },
  { first: "Samweli", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Pangani" },
  { first: "Sekela", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Muheza" },
  { first: "Godfrey", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mkinga" },
  { first: "Atupelye", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kibaha" },
  { first: "Amos", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kisarawe" },
  { first: "Tunu", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mkuranga" },
  { first: "Ezekiel", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Rufiji" },
  { first: "Stella", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kibiti" },
  { first: "Innocent", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mvomero" },
  { first: "Flora", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Gairo" },
  { first: "Goodluck", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kilosa" },
  { first: "Glory", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Ulanga" },
  { first: "Omari", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Malinyi" },
  { first: "Evelyn", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kilombero" },
  { first: "Yohana", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mufindi" },
  { first: "Dora", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kilolo" },
  { first: "Suleiman", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Makete" },
  { first: "Lulu", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Ludewa" },
  { first: "Yahya", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Wanging'ombe" },
  { first: "Diana", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mbarali" },
  { first: "Godlisten", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Kyela" },
  { first: "Rose", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Rungwe" },
  { first: "Musa", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Ileje" },
  { first: "Happiness", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mbozi" },
  { first: "Amiri", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Momba" },
  { first: "Agnes", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Kalambo" },
  { first: "Idris", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Nkasi" },
  { first: "Frida", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Mpimbwe" },
  { first: "Emanuel", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Tanganyika" },
  { first: "Anna", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Nsimbo" },
  { first: "Japhet", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Mlele" },
  { first: "Jackline", gender: "female", country: "Tanzania", flag: "🇹🇿", city: "Chunya" },
  { first: "Lazaro", gender: "male", country: "Tanzania", flag: "🇹🇿", city: "Songwe" }`;

content = content.replace(/const RAW_FIRST_NAMES_DB: \{.*\} \]/s, (match) => {
  return match.replace(/\]$/, `,\n${tzNames}\n]`);
});

// 3. Update rawSwahiliComments to match requirements EXACTLY
const newComments = `export const rawSwahiliComments: { text: string; replies: { name: string; text: string; time: string }[] }[] = [
  { text: "Kiukweli mwanzoni nilikua siamini kama haya mambo ya mtandaoni yanalipa, lakini nilivyojiunga na kuanza kudhibitisha oda, nimetoa elfu 50 yangu ya kwanza leo asubuhi bila longolongo yoyote! 🙏🙏", replies: [] },
  { text: "Inalipa sana aisee 🔥", replies: [] },
  { text: "Hii fursa ni mkombozi kwa vijana wengi ambao hawana ajira mtaani. Pesa inaingia fasta tu ukifanya kazi yako kwa umakini.", replies: [] },
  { text: "Asante sana kwa aliyenishirikisha hii kitu. Withdraw ziko very instant. Nimeomba kutoa pesa ndani ya dakika 3 imeingia kwenye M-pesa yangu.", replies: [] },
  { text: "Daaah nilichelewa sana kujua hii platform 😭😭😭 nimepoteza muda mwingi sana. Sasa hivi ni kazi tu na kuvuna pesa.", replies: [{name: "Amina J.", text: "Bora umejua sasa 👏 fursa ndio hii.", time: "Dakika 4 zilizopita"}] },
  { text: "Ni kweli inalipa?", replies: [{name: "Juma", text: "Ndio inalipa sana kaka, mimi nimeanza wiki iliyopita na nimeshatoa hela mara mbili.", time: "Dakika 10 zilizopita"}] },
  { text: "Guys mimi nilikuwa naogopa matapeli, lakini hapa nimehakikisha asilimia 100 ni salama. Zile kamisheni za asilimia 5 zinasaidia sana kusogeza siku.", replies: [] },
  { text: "Pesa nje nje 💸💸", replies: [] },
  { text: "Kwa mtu yeyote anayehitaji side hustle, hii ndio yenyewe. Hutumii nguvu nyingi, wewe ni kudhibitisha oda tu na hela yako inaingia.", replies: [] },
  { text: "Nimevuta laki 2 leo, weekend imeanza vizuri sana kwangu 🍻", replies: [] },
  { text: "Nawezaje kujiunga jamani?", replies: [{name: "Zuhura", text: "Fuata maelekezo ya kujisajili hapo juu, ni rahisi sana dada.", time: "Saa 1 lililopita"}] },
  { text: "Withdrawal zao hazina makato makubwa, ukitoa hela yako unapata karibu yote, hii kampuni iko fair sana kwa kweli.", replies: [] },
  { text: "Hii ni legit 100% 🔥", replies: [] },
  { text: "Jana usiku nilifanya kazi nikapata oda 15 mfululizo, asubuhi hii nimeamka nimekuta balance imesoma vizuri sana. Nimetuma withdrawal na imekubali chap.", replies: [] },
  { text: "Nilikuwa na mashaka sana kama kweli wanatoa pesa, lakini leo nimethibitisha. Nimepokea ujumbe wa Tigo Pesa sasa hivi.", replies: [] },
  { text: "Mambo ni motooo 🔥🔥🔥", replies: [] },
  { text: "Kazi nyepesi, malipo ya uhakika. Hakuna stress ya kuamka asubuhi kuwahi daladala.", replies: [] },
  { text: "Kuna aliyewahi kutoa zaidi ya laki 5 hapa?", replies: [{name: "Baraka", text: "Mimi nilitoa laki 6 wiki iliyopita, inategemea na juhudi yako tu.", time: "Masaa 2 yaliyopita"}] },
  { text: "Ahsanteni sana, nimefanikiwa kutoa elfu 80 yangu ya kwanza. Hii system ni nzuri na haina complication yoyote.", replies: [] },
  { text: "Nzuri sana hii! 👏", replies: [] },
  { text: "Sijawahi kujutia kujiunga hapa, mwanzo niliweka mtaji mdogo sasa hivi napiga hela tu.", replies: [] },
  { text: "Hii biashara iko salama sana, platform yao ina security nzuri na hela yako huwezi kupoteza.", replies: [] },
  { text: "Pesa inaingia wakati wowote, yaani hata usiku wa manane ukiomba kutoa, inatoka tu. Safi sana uongozi 👏👏", replies: [] },
  { text: "Nani mwingine amepata withdrawal asubuhi hii? Mimi nimepokea yangu tayari.", replies: [] },
  { text: "Iko poa sana 💯", replies: [] },
  { text: "Nimewashirikisha na marafiki zangu nao wameanza kutengeneza pesa. Hakuna kuficha fursa.", replies: [] },
  { text: "Mfumo unasoma haraka, ukithibitisha tu oda, mzigo unasoma kwenye account balance papo hapo.", replies: [] },
  { text: "Hii inasaidia sana hasa kwa sisi wanafunzi wa vyuo, tunapata hela ya kujikimu bila kuomba nyumbani kila siku.", replies: [] },
  { text: "Kazi nzuri, malipo papo hapo ✅", replies: [] },
  { text: "Kama bado unalaza damu unapitwa na mengi sana, amka uanze kazi ujionee tofauti.", replies: [] },
  { text: "Ukweli mchungu ni kwamba fursa zipo, ila watu wanapenda kubet badala ya kufanya kazi za uhakika kama hizi.", replies: [] },
  { text: "Nina siku tatu tangu nijiunge, nimesharudisha mtaji wangu na sasa natengeneza faida tupu. Mungu ibariki hii kampuni.", replies: [] },
  { text: "Good job 👏", replies: [] },
  { text: "Hakuna kiwango cha ukomo, ukiweza kudhibitisha oda 100 kwa siku ni wewe tu na speed yako.", replies: [] },
  { text: "Nimeipenda sana hii, inakupa uhuru wa kufanya kazi ukiwa popote pale.", replies: [] }
];`;

content = content.replace(/export const rawSwahiliComments: \{ text: string; replies: \{ name: string; text: string; time: string \}\[\] \}\[\] = \[\s*\{[\s\S]*?\];/s, newComments);


// 4. Modify buildCompliantComments and buildCompliantLivePayouts to use targetCountry="Tanzania"
// This ensures ALL generated names in comments and live notifications are from the newly added Tanzanian database.
content = content.replace(/const customer = generateDistinctCustomer\(usedBaseNames, usedFullNames\);/g, 'const customer = generateDistinctCustomer(usedBaseNames, usedFullNames, "Tanzania");');


// 5. Version bump for freshness
content = content.replace(/STORAGE_VERSION_TAG = "ov_v[0-9a-z_]+"/, 'STORAGE_VERSION_TAG = "ov_v38_real_tz_names_social"');

fs.writeFileSync('src/data.ts', content);
console.log("Updated names and comments.");
